### ISSUE TITLE
Label does not match for single geog selection

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#363] opened 2017-12-27 22:04 UTC

**Comment by EricaMaurer** [comment] 2017-12-27 22:04
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fa2e2881b17cbe1023590b0b4aac415e0b41f8fd892fafa42062c80d55b98e30063e937f03a6aa8318b500bf218f4b84b4be834dc7e93e37aa.JPG)

**Comment by chriswhong** [comment] 2018-01-02 15:22
Not sure if this is reproducible, investigate and see if it's still an issue.

**Comment by EricaMaurer** [comment] 2018-01-02 20:52
https://nyc-factfinder.planninglabs.nyc/profile/358/economic

**Comment by EricaMaurer** [comment] 2018-01-02 20:56
Same with PUMAs: https://nyc-factfinder.planninglabs.nyc/profile/389/economic

**Comment by chriswhong** [comment] 2018-01-05 19:13
Could not reproduce this on `develop` right now.  Closing

**Closed by chriswhong** 2018-01-05 19:13 UTC
Labels: bug, to do
