### ISSUE TITLE
User can select geometries based on decennial census variable

### ISSUE THREAD

**Issue by JoelAAlvarez** [NYCPlanning/labs-nyc-factfinder#244] opened 2017-12-01 19:52 UTC
Geographic filtering-- limit selectable areas on the map where geographies match user specifications (eg. user selected to limit geographies to those where Hispanic population is 50% or more)

**Comment by JoelAAlvarez** [comment] 2017-12-01 19:53
[Select by Variable List - For Decennial.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46db9196268197e98df0ff75a54ff9952b4a2233050db03f30c8a30eb0503b250a0c1bf21f010e18eee59b6be4e96625d91819e7c3685621ce6913a8e98017b755ee248b4f83e2b98e48c0ec3437fb99cd1e604a5a45d0b50877b29359c95ffc4ae44c57a516316aee7e3e7f4e8653.xlsx)

**Comment by EricaMaurer** [comment] 2017-12-18 14:26
Duplicate of #21

**Closed by EricaMaurer** 2017-12-18 14:26 UTC
Labels: Later
