### ISSUE TITLE
'Jump to section' only works once

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#447] opened 2018-01-17 19:56 UTC

**Comment by andycochran** [comment] 2018-02-13 15:06
Duplicate of #304

**Comment by EricaMaurer** [comment] 2018-07-03 18:47
This is still an issue. It works fine with the first geography selected no matter. Once you return to the map and change selection, the jump-to-section feature no longer works.

**Closed** 2018-07-17 14:00 UTC
Labels: bug, in progress
