### ISSUE TITLE
Decennial: Percentage point difference calculation needs to be multiplied by 100 or format column as percent

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#573] opened 2018-03-08 17:11 UTC

**Comment by allthesignals** [comment] 2018-03-09 22:53
@EricaMaurer I guess that the issue is that most of the pctg pt values are coming out as 0.0 bc they're not converted into display percentages.

**Comment by allthesignals** [comment] 2018-03-09 22:54
Next time we should use the issue template <3

**Comment by allthesignals** [comment] 2018-03-09 22:55
Change percentage point seems to work

**Comment by allthesignals** [comment] 2018-03-09 22:59
I think this is an API issue because decennial and acs share the same templates.

**Comment by allthesignals** [comment] 2018-03-09 23:07
API is multiplying by 100 for the change pct pt but not the difference pct pt, and expects the template to handle one over the other.

**Comment by allthesignals** [comment] 2018-03-09 23:16
There's too much being multiplied in some places and not in others so to avoid regressions I'll just multiply in decennial - worried this may affect single geogs.

**Comment by allthesignals** [comment] 2018-03-09 23:17
No effect - deploying and closing

**Comment by EricaMaurer** [comment] 2018-03-09 23:17
Makes sense. Thanks

**Closed by allthesignals** 2018-03-09 23:17 UTC
Labels: in progress
