### ISSUE TITLE
Shareable link bug

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#236] opened 2017-12-01 14:06 UTC
When user shares a link for NTA selections..and goes back to the map selection appears as CTs.. and when user returns to profile 0 geogs appear

**Comment by chriswhong** [comment] 2017-12-01 14:17
Sounds like we are not actually writing the current selection in the selection service when we get it from the backend.  

Should be a quick fix, although it may make more sense to not use the service at all and have both `index` and `report` depend on a query param to know what is selected.

**Comment by andycochran** [comment] 2017-12-08 16:10
Relatedly, when you load NTA profiles and go back to the map, the selection does show NTA(s) even though you're in Census Tract selection mode. AND even though you can't unselect NTA(s) they're part of the count in the "View Profile" button. AND you can add Tracts to that selection. 

In the image below, I've refreshed a profile for Steinway, gone to the map, then added 107.01 to the selection—which changed the count from 1 (a single NTA) to 2 (one NTA and one Tract). 

![image](https://user-images.githubusercontent.com/409279/33773889-71d4bc4e-dc07-11e7-836c-2eb8350177a2.png)

**Comment by chriswhong** [comment] 2018-02-07 18:35
I'm not able to reproduce this at the moment, but let's leave it open and check again once things settle down after the API refactor.

**Comment by chriswhong** [comment] 2018-02-12 18:13
Still can't reproduce this anymore, closing.

**Closed by chriswhong** 2018-02-12 18:13 UTC
Labels: bug, to do
