### ISSUE TITLE
Expand choropleth maps

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#226] opened 2017-11-29 18:43 UTC
Choropleths will usually be at the NTA or PUMA level. The approach will be to make the choropleth overlay an option when doing the "select by variable" feature. Customer will provide guidance on styling and breaks for each choropleth.

**Comment by chriswhong** [comment] 2017-12-01 21:03
Duplicate of #23, let's use that one to specify which choropleths we want to accomplish in the next sprint

**Closed by chriswhong** 2017-12-01 21:03 UTC
Labels: SELECT, to do
