### ISSUE TITLE
User can see tabs for different data types and high-level sections

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#9] opened 2017-10-23 16:05 UTC
Tabs include:
-Census
-Demographics (ACS)
-Social (ACS)
-Economics (ACS)
-Housing (ACS)

**Comment by chriswhong** [comment] 2017-10-30 14:53
Duplicate of #68

**Closed** 2017-10-30 14:53 UTC
Labels: REPORT
