### ISSUE TITLE
Top- and bottom- coded median values

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#157] opened 2017-11-14 14:18 UTC
User will see top- and bottom- coded median values as gray.

**Comment by EricaMaurer** [comment] 2017-11-14 14:19
Top- and bottom- coded values for each median calculation

[TopAndBottomCodedVals_06-10and11-15.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46dc9b8a028c878b80fdab4ca97eff902c42117225179c7b26c8b278be4c7f505e424fa953444d04bea6d37ef5f22e7a985902b8d9395d70973f19a4ecd61bbf01bc748e4b81b6b8835edcfa7f74b9dfd0126754505a9bf54f34a9934acd59f64de74454a21b3066e3647b.xlsx)

**Comment by chriswhong** [comment] 2017-12-04 16:58
Duplicate of #29

**Comment by JoelAAlvarez** [comment] 2017-12-07 17:06
This issue was also intended to be used to help users identify top- and bottom-coded values, so I'm attaching two tables below (one for 2006-2010 and one for 2012-2016) that show top-/bottom-coded values for each respective dataset (and each level of geography) and how the top-/bottom-coded values should appear in the profiles.

[TopAndBottomCodedVals_12-16.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46dc9b8a028c878b80fdab4ca97eff902c42117225179c7a22c8b27efd0e39111d0014f9121c4d4eeefc807eaee23e74db5e03e585395b74c63b45a9bc861fbb08a83c990dd4e8e8d51199a26867f5819d4e3914041d88fd5b33a69b42c051f448f300.xlsx)
[TopAndBottomCodedVals_06-10.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46dc9b8a028c878b80fdab4ca97eff902c42117225179c7b26c8b278fd0e39111d0014f9121c4d4eeefc807eaee23e74db5e03e585395b74c63b45a9bc861fbb08a83c990dd4e8e8d51199a26867f5819d4e3914041d88fd5b33a69a42cf5af243f300.xlsx)

**Comment by andycochran** [comment] 2017-12-07 17:43
So, in addition to being grayed out… 
- Top-coded  values should have a "+" suffix
- Bottom-coded values should have a "-" suffix

**Comment by EricaMaurer** [comment] 2017-12-26 14:43
If a median estimate is greater than the top-coded value, it should appear as the top-coded value.

**Comment by allthesignals** [comment] 2018-02-11 04:21
> User will see top- and bottom- coded median values as gray.

So when they're top-coded they become unreliable, right?
I think this can be done with formulas through the config files.

**Comment by EricaMaurer** [comment] 2018-02-11 05:25
Yes, they become unreliable and should be gray. This issue is also to display the value as the top- or bottom- coded value.

**Comment by allthesignals** [comment] 2018-02-11 05:26
@EricaMaurer gotcha, thanks - just wanted to confirm.

**Closed** 2018-02-13 19:50 UTC
Labels: enhancement, in progress
